# Generated by Django 4.2.6 on 2023-10-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("firma", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("telefon", models.CharField(max_length=30)),
                ("place", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("plz", models.CharField(max_length=250)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
